AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  HereAppId:
    Type: String
    Description: HERE Maps API App ID (https://developer.here.com/faqs#access-control)
  HereAppCode:
    Type: String
    Description: HERE Maps API App Code (https://developer.here.com/faqs#access-control)

Resources:
  PlacesFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: nodejs6.10
      Handler: places.placesGET
      Description: 'Find (e.g., search for name, type, category), discover (e.g., look into address, contact info) and interact with POI information (e.g., enable user reviews, photos).'
      Environment:
        Variables:
          HERE_APP_ID: !Ref HereAppId
          HERE_APP_CODE: !Ref HereAppCode
      Events:
        GET:
          Type: Api
          Properties:
            Path: /places
            Method: get
Outputs:
  HereApiURL:
    Description: "AWS API Gateway URL for Here.com Places API (CIT)."
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/"